spring:
    application:
        name: user-cloud
    cloud:
        config:
            discovery:
                service-id: config-cloud
                enabled: true
            profile: dev
    zipkin:
        base-url: http://localhost:9411/